{% set version = "1.1.0" %}

package:
  name: "cyanure"
  version: {{ version }}

source:
  url: https://github.com/inria-thoth/cyanure/releases/download/{{ version }}/cyanure-{{ version }}.tar.gz
  sha256: ab0681c3a4379eb57c3dfc79d6284b733d30fbe57f5ba9b1c0ea9501d1481cf9
    
build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - python                                 # [build_platform != target_platform]
    - libgomp  # [linux]
    - intel-openmp  # [win]
  host:
    - python
    - libblas
    - liblapack
    - numpy >=1.21.6
    - pip
  run:
    - python
    - scipy
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    

test:
  imports:
    - cyanure
  source_files:
   - test/*.py
  requires:
    - pytest
    - pandas
  commands:
    - pytest

about:
  home: https://inria-thoth.github.io/cyanure/welcome.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Toolbox for Empirical Risk Minimization'
  description: | 
   Cyanure is an open-source C++ software package with a Python 3 interface. 
   The goal of Cyanure is to provide state-of-the-art solvers 
   for learning linear models, based on stochastic variance-reduced stochastic optimization 
   with acceleration mechanisms and Quasi-Newton principles. 
  dev_url: https://github.com/inria-thoth/cyanure
  doc_url: https://inria-thoth.github.io/cyanure/welcome.html

extra:
  recipe-maintainers:
    - thomasryck
    - jmairal
