{% set version = "1.1.0" %}

package:
  name: "cyanure"
  version: {{ version }}

source:
  url: https://github.com/inria-thoth/cyanure/releases/download/{{ version }}/cyanure-{{ version }}.tar.gz
  sha256: f1669e11564aafb869a596a85de94e0eb5ed914c1294d191627547ecd556e225
    
build:
  number: 3
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - numpy <=1.23.5  # [py < 3.11]
    - numpy >=1.23.5  # [py > 3.10]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - intel-openmp  # [win]
  host:
    - python
    - setuptools
    - libblas
    - liblapack
    - numpy <=1.23.5  # [py < 3.11]
    - numpy >=1.23.5  # [py > 3.10]
    - pip
  run:
    - python
    - scipy
    - scikit-learn
    

test:
  imports:
    - cyanure
  source_files:
   - test/*.py
  requires:
    - pytest
    - pandas
    - libsvmdata
  commands:
  # VM is too small for tests on Windows
    - pytest  # [osx]
    - pytest  # [linux]

about:
  home: https://inria-thoth.github.io/cyanure/welcome.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Toolbox for Empirical Risk Minimization'
  description: | 
   Cyanure is an open-source C++ software package with a Python 3 interface. 
   The goal of Cyanure is to provide state-of-the-art solvers 
   for learning linear models, based on stochastic variance-reduced stochastic optimization 
   with acceleration mechanisms and Quasi-Newton principles. 
  dev_url: https://github.com/inria-thoth/cyanure
  doc_url: https://inria-thoth.github.io/cyanure/welcome.html

extra:
  recipe-maintainers:
    - thomasryck
    - jmairal
