{% set version = "1.2.2" %}

package:
  name: "cyanure"
  version: {{ version }}

source:
  url: https://github.com/inria-thoth/cyanure/releases/download/{{ version }}/cyanure-{{ version }}.tar.gz
  sha256: 2c0bd3b833278fabf518732c6571fadcad3914dcb2d609b5cb34bc83aeecc441
    
build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - numpy                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - intel-openmp  # [win]
  host:
    - python
    - setuptools
    - libblas
    - liblapack
    - openblas  # provides cblas.h headers (setup.py does #include <cblas.h>)
    - numpy
    - pip
  run:
    - python
    - scipy
    - scikit-learn >=1.6
    

test:
  imports:
    - cyanure
  source_files:
   - test/*.py
  requires:
    - pytest
    - pandas
    - libsvmdata
  commands:
  # Skip tests that download external LibSVM datasets (no network in CI).
  # VM is too small for tests on Windows
    - pytest -k "not finance and not rcv1"  # [osx]
    - pytest -k "not finance and not rcv1"  # [linux]

about:
  home: https://inria-thoth.github.io/cyanure/welcome.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Toolbox for Empirical Risk Minimization'
  description: | 
   Cyanure is an open-source C++ software package with a Python 3 interface. 
   The goal of Cyanure is to provide state-of-the-art solvers 
   for learning linear models, based on stochastic variance-reduced stochastic optimization 
   with acceleration mechanisms and Quasi-Newton principles. 
  dev_url: https://github.com/inria-thoth/cyanure
  doc_url: https://inria-thoth.github.io/cyanure/welcome.html

extra:
  recipe-maintainers:
    - thomasryck
    - jmairal
