{% set version = "1.0.0" %}

package:
  name: "cyanure"
  version: {{ version }}

source:
  url: https://github.com/thomasryck/cyanure/archive/{{ version }}/cyanure-{{ version }}.tar.gz
  sha256: e5bab6277a74adade8c9e952af72b1298d35809de200d6e460078907a6e47820
    
build:
  number: 0
  skip: True  [py==310]
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - python
    - libgomp  # [linux]
    - intel-openmp  # [win]
  host:
    - python
    - libblas
    - liblapack
    - numpy >=1.18.0
    - pip
  run:
    - python
    - scipy
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    

test:
  imports:
    - cyanure
  source_files:
   - test/*.py
  requires:
    - pytest
    - pandas
  commands:
    - pytest

about:
  home: https://inria-thoth.github.io/cyanure/welcome.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Toolbox for Empirical Risk Minimization'
  description: | 
   Cyanure is an open-source C++ software package with a Python 3 interface. 
   The goal of Cyanure is to provide state-of-the-art solvers 
   for learning linear models, based on stochastic variance-reduced stochastic optimization 
   with acceleration mechanisms and Quasi-Newton principles.
  dev_url: https://github.com/inria-thoth/cyanure
  doc_url: https://inria-thoth.github.io/cyanure/welcome.html

extra:
  recipe-maintainers:
    - thomasryck
    - jmairal
